### ISSUE TITLE
Incompatibility with floodgate

### ISSUE THREAD

**Issue by HaHaWTH** [ruViolence/Reaper#56]
**Describe the bug**
The floodgate throws an error when enabling, on paper 1.12.2 it works fine

**To Reproduce**
Install latest version of floodgate on Reaper  [Download](https://geysermc.org/download#floodgate)
Start the server
Then plugin errored

**Plugins**
Show the output of /plugins here.
AuthMe, floodgate

**Version**
Show the output of /version here

git-Reaper-"19667e4"

**Misc**
Anything else helpful not belonging in the categories above.

![IMG_3622](https://github.com/ruViolence/Reaper/assets/102713261/1b74407d-8795-40b3-9eac-e80d6e7740ff)

**Comment by ruViolence** [comment]
Open `cache/patched_1.12.2.jar` as a zip file and remove the folder located at `io/papermc/paper/configuration` from it. After that, use `patched_1.12.2.jar` to start the server, otherwise paperclip will overwrite the file again.

Floodgate checks for the presence of a new Paper config file, but it's empty here. It was added just to disable the built-in packet limiter in ViaVersion.

**Comment by HaHaWTH** [comment]
> Open `cache/patched_1.12.2.jar` as a zip file and remove the folder located at `io/papermc/paper/configuration` from it. After that, use `patched_1.12.2.jar` to start the server, otherwise paperclip will overwrite the file again.
> 
> Floodgate checks for the presence of a new Paper config file, but it's empty here. It was added just to disable the built-in packet limiter in ViaVersion.

Thanks! It‘s solved now
